"""Chat UI regression. Run only against the isolated QA database prepared by ui-admin.py."""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = 'http://127.0.0.1:3210'
output = Path('test-results')
output.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='msedge', headless=True)
    context = browser.new_context(storage_state=str(output / 'admin-state.json'), viewport={'width':1440,'height':1000})
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(BASE, wait_until='networkidle')
    card = page.locator('.character-card').filter(has_text='联调角色甲')
    expect(card).to_be_visible()
    page.screenshot(path=str(output / 'discover-configured.png'), full_page=True)
    card.get_by_role('button', name='开始对话').click()
    page.wait_for_url('**/chat/**')
    expect(page.get_by_role('textbox', name='输入消息')).to_be_visible()
    page.get_by_role('textbox', name='输入消息').fill('你好，这是私聊功能验证。')
    page.get_by_role('button', name='发送消息', exact=True).click()
    expect(page.locator('.theirs .message-bubble').last).to_contain_text('本地演示回复', timeout=20000)
    expect(page.get_by_role('button', name='停止生成')).not_to_be_visible()
    expect(page.locator('.mine .message-bubble').last).to_contain_text('私聊功能验证')
    page.screenshot(path=str(output / 'private-chat-desktop.png'), full_page=True)
    page.locator('.remember-message').last.click()
    dialog = page.get_by_role('dialog')
    expect(dialog).to_be_visible()
    dialog.locator('textarea').fill('喜欢轻松的对话，也喜欢听雨声。')
    dialog.get_by_role('button', name='保存记忆').click()
    expect(dialog).not_to_be_visible()
    expect(page.locator('.info-memories')).to_contain_text('喜欢轻松的对话')
    with page.expect_download() as export:
        page.get_by_role('button', name='导出对话').click()
    export.value.save_as(str(output / 'conversation-export.json'))
    assert len(json.loads((output / 'conversation-export.json').read_text(encoding='utf-8'))['messages']) >= 2
    print('PASS private chat / streaming / explicit memory / export')

    page.get_by_role('link', name='群聊空间', exact=True).click()
    page.get_by_role('button', name='创建群聊', exact=True).click()
    dialog = page.get_by_role('dialog')
    dialog.get_by_label('群聊名称').fill('一次午后的相聚')
    dialog.get_by_role('button', name='联调角色甲', exact=True).click()
    dialog.get_by_role('button', name='联调角色乙', exact=True).click()
    dialog.locator('textarea').fill('一间安静的茶室，窗外是小马利亚的午后。')
    page.screenshot(path=str(output / 'group-create-dialog.png'), full_page=True)
    dialog.get_by_role('button', name='开始这段群聊').click()
    page.wait_for_url('**/chat/**')
    expect(page.get_by_role('textbox', name='输入消息')).to_be_visible()
    before = page.locator('.theirs').count()
    page.get_by_role('textbox', name='输入消息').fill('这是普通群消息，不需要角色回应。')
    page.get_by_role('button', name='发送消息', exact=True).click()
    expect(page.locator('.mine .message-bubble').last).to_contain_text('普通群消息')
    expect(page.get_by_role('button', name='停止生成')).not_to_be_visible()
    assert page.locator('.theirs').count() == before
    page.get_by_role('button', name='提及角色', exact=True).click()
    expect(page.get_by_role('menu')).to_be_visible()
    page.screenshot(path=str(output / 'group-mention-menu.png'), full_page=True)
    page.get_by_role('menuitem', name='联调角色甲').click()
    expect(page.get_by_role('textbox', name='输入消息')).to_have_value('@联调角色甲 ')
    page.get_by_role('textbox', name='输入消息').fill('@联调角色甲 你今天过得怎么样？')
    page.get_by_role('button', name='发送消息', exact=True).click()
    expect(page.locator('.theirs')).to_have_count(before + 1, timeout=20000)
    expect(page.get_by_role('button', name='停止生成')).not_to_be_visible()
    page.screenshot(path=str(output / 'group-chat-desktop.png'), full_page=True)
    print('PASS group creation / plain message without AI / mention picker / one selected reply')

    page.get_by_role('textbox', name='输入消息').fill('@')
    expect(page.get_by_role('menu')).to_be_visible()
    page.get_by_role('textbox', name='输入消息').press('ArrowDown')
    expect(page.get_by_role('menuitem').first).to_be_focused()
    page.keyboard.press('ArrowDown')
    expect(page.get_by_role('menuitem').nth(1)).to_be_focused()
    selected_name = page.get_by_role('menuitem').nth(1).locator(':scope > span').nth(1).inner_text()
    page.keyboard.press('Enter')
    expect(page.get_by_role('textbox', name='输入消息')).to_have_value('@' + selected_name + ' ')
    page.get_by_role('textbox', name='输入消息').fill('')
    page.set_viewport_size({'width':390,'height':844})
    page.wait_for_function("document.querySelector('.sidebar').getBoundingClientRect().right <= 0")
    assert not page.evaluate('document.documentElement.scrollWidth > window.innerWidth')
    assert page.evaluate('document.documentElement.scrollHeight <= window.innerHeight + 1'), 'Chat composer must stay inside the mobile viewport'
    page.screenshot(path=str(output / 'group-chat-mobile.png'), full_page=True)
    page.get_by_role('button', name='查看对话详情').click()
    expect(page.locator('.chat-info')).to_be_visible()
    page.get_by_role('button', name='关闭对话详情').click()
    page.get_by_role('button', name='对话设置').click()
    expect(page.get_by_role('dialog')).to_be_visible()
    assert page.locator('.modal-backdrop').evaluate('el => el.getBoundingClientRect().top') == 0
    page.screenshot(path=str(output / 'chat-settings-mobile.png'), full_page=True)
    page.keyboard.press('Escape')
    expect(page.get_by_role('dialog')).not_to_be_visible()
    print('PASS mention keyboard / mobile layout / story panel / dialog Escape')

    page.get_by_role('button', name='打开导航').click()
    page.get_by_role('link', name='记忆档案', exact=True).click()
    expect(page.locator('.memory-note').first).to_contain_text('喜欢轻松的对话')
    page.locator('.memory-note').first.get_by_role('button', name='编辑记忆').click()
    page.get_by_role('dialog').locator('textarea').fill('喜欢听雨声，想在下一次对话里去图书馆。')
    page.get_by_role('dialog').get_by_role('button', name='保存记忆').click()
    expect(page.get_by_role('dialog')).not_to_be_visible()
    expect(page.locator('.memory-note').first).to_contain_text('下一次对话里去图书馆')
    page.screenshot(path=str(output / 'memories-mobile.png'), full_page=True)
    page.emulate_media(reduced_motion='reduce')
    assert page.locator('.page-enter').evaluate("el => getComputedStyle(el).animationName") == 'none'
    assert not errors, errors
    print('PASS memory editing / reduced motion / no JS errors')
    context.close()
    browser.close()
